#! /usr/bin/env ruby

require "yard"

# Handles the YARD registry parsing and Markdown content generation.
# See also main script below
class APIDocsGenerator
  attr_reader :repo_name
  attr_reader :repo_base_path
  attr_reader :destination_file

  def initialize(repo_name)
    @repo_name = repo_name

    # Set up paths
    case repo_name
    when :plugin
      @repo_base_path = "../newsmast-mastodon"
      @destination_file = "./src/10_plugin_api_documentation.md"
    when :dashboard
      @repo_base_path = "../newsmast-dashboard"
      @destination_file = "./src/11_dashboard_api_documentation.md"
    end
  end

  def generate
    puts "1. Regen docs"

    puts `cd #{repo_base_path} && rm -rf .yardoc && bundle exec yard list`

    puts "2. Loading registry"

    # Load the YARD registry that was generated by the `yard list` command and
    # find all the methods tagged by `@resource`
    YARD::Registry.load!("#{repo_base_path}/.yardoc")
    tagged_methods = YARD::Registry.all(:method).select { |mth| mth.tags.find { it.tag_name == "resource" } }
    #puts tagged_methods.inspect

    puts "3. Writing to #{destination_file}"

    File.open(destination_file, "w") do |f|
      f.puts "<!-- AUTOGENERATED ON #{Time.now} BY script/generate_api_docs.rb, DO NOT EDIT! -->\n\n"

      # Get the repo-specific preamble from calling script
      yield f
      f.puts

      # Loop through the tagged methods and produce the block of Markdown for that
      # API resource
      tagged_methods.each do |tagged|
        produce_markdown_for_tagged(f, tagged)
      end
    end
  end

  private

  def parse_tag_text_for_yard_comment(text)
    type, param, description = text.match(/(\[\w+\])\s([^\s]+)\s(.*)?/)[1..]
    <<~MARKDOWN
      * **#{param}** (_#{type.delete_prefix("[").delete_suffix("]")}_) - #{description}
    MARKDOWN
  end

  def produce_markdown_for_tagged(f, tagged)
    f.puts "## #{tagged.tag("action").text} #{tagged.tag("resource").text}\n\n"
    f.puts "#{tagged.docstring}\n\n"

    tagged.tags("required").each_with_index do |req_tag, index|
      f.puts "\n### Required Parameters\n\n" if index.zero?
      f.puts parse_tag_text_for_yard_comment(req_tag.text)
    end
    tagged.tags("optional").each_with_index do |opt_tag, index|
      f.puts "\n### Optional Parameters\n\n" if index.zero?
      f.puts parse_tag_text_for_yard_comment(opt_tag.text)
    end
    tagged.tags("response_field").each_with_index do |opt_tag, index|
      f.puts "\n### JSON Response Fields\n\n" if index.zero?
      f.puts parse_tag_text_for_yard_comment(opt_tag.text)
    end
    if tagged.tag("example_response")
      f.puts "\n## Example Response\n\n"
      f.puts tagged.tag("example_response").text
    end

    f.puts "\n---\n\n"
  end
end

### Main script ###

case ARGV[0]&.strip
when "plugin"
  APIDocsGenerator.new(:plugin).generate do |f|
    f.puts "# API Documentation for the Mastodon Plugin Gem"
  end
when "dashboard"
  APIDocsGenerator.new(:dashboard).generate do |f|
    f.puts "# API Documentation for the Admin Dashboard"
  end
when nil
  puts "This script finds @resource YARD tags in the Newsmast plugin and dashboard repos"
  puts "and uses them to generate Markdown files with the API documentation.\n\n"
  puts "Usage: script/generate_api_docs.rb [plugin|dashboard]\n\n"
else
  puts "Unknown API generation repo `#{ARGV[0]}`, must be `plugin` or `dashboard`"
end
